server:
   port: 9080
application:
   name: ^project.artifactId^
   description: ^project.name^
   version: ^project.version^
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ^project.artifactId^
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: customer-microservice
        uri: lb://customer-microservice
        predicates:
        - Path=/customers/**
        filters:
        - RewritePath=/customers/(?<path>.*), /$\{path}
      - id: loan-application-microservice
        uri: lb://loan-application-microservice
        predicates:
          - Path=/customers/**
        filters:
          - RewritePath=/loanapplications/(?<path>.*), /$\{path}
